#pragma once

#include <numeric>
#include <compare>
#include <utility>
#include <string>
#include <iostream>
#include <vector>
#include <cassert>
#include <memory>
#include <algorithm>
#include <type_traits>
#include <ranges>
#include <iterator>
#include <filesystem>
#include <functional>
#include <thread>
#include <mutex>
#include <chrono>
#include <concepts>
#include <thread>
#include <variant>
#include <cstdint>
#include <cstdio>
#include <bit>
#include <compare>
#include <coroutine>
#include <format>
#include <numbers>
#include <source_location>
#include <span>
#include <syncstream>
#include <version>
#include <typeinfo>
